### ISSUE TITLE
[Bug]: Build jobs are failing after upgrade to 9.2 where an installed dependency isn't being seen

### ISSUE THREAD

**Issue by nickgoddard777** [microsoft/AL-Go#2354]
### AL-Go version

9.2

### Describe the issue

We have a Repo that has 3 projects, each has a varying number of apps in. One of the apps (I'll call it AppA for this explantion) has a depenedncy on Continia Document Capture. The Test Current that we ran on Monday night passed. Then on Tuesday we had a PR which didn't change anything in AppA, the PR Build failed with the error 'Unexpected error when running action. Error Message: Extension compilation failed src/features/ContiniaManagement.Codeunit.al(15,27): error AL0185: Codeunit 'CDC Module License' is missing src/features/ContiniaManagement.Codeunit.al(22,32)', This is just part of the error there were failures of all the referencess to Continia. The version of Continia Document Capture hasn't changed and was the same in both the passing and fialing Test Current Builds. We are getting Continia apps from their nuget feed at https://pkgs.dev.azure.com/continia-repository/ContiniaBCPublicFeeds/_packaging/AppSourceApps/nuget/v3/index.json
The Test Current then failed both Tuesday night and Wednesday night, Update to 9.2 happend about 30 mins before the Tuesday night Test Current ran. The only other change is that we moved this repo to use a GitHub runner rather than our Self-Hosted runner as we were having seperate issues with our runners.
We now have a further 2 PRs that are failing and I'm unable to get any of them to pass and have urgent deadlines for the client.

### Expected behavior

As Contina Document Capture is showing in the Installed Apps list I would expect AppA to be published correctly.

### Steps to reproduce

Have an app that has a dependency on Continia Document Management. Add a link to a Continia Document Management object in a codeunit. Upgrade the app to AL-Go 9.2. Run Test Current.

### Additional context (logs, screenshots, etc.)

[Obfuscated-Log.txt](https://github.com/user-attachments/files/31514518/Obfuscated-Log.txt)

**Comment by aholstrup1** [comment]
@nickgoddard777 Would you be able to provide some logs for the run that succeeded earlier in the week? That might help us understand better why it suddenly started failing. As far as I can see this is not an area we've made a whole lot of changes in recently so I'm not sure AL-Go v9.2 was the cause. 

Based on the logs you provided it looks like we find the same dependency with the same version in both Continias own feed and in the AppSourceSymbols feed. We choose to use the AppSourceSymbols feed which we probably shouldn't. Once quick workaround you could try on your side is to set the trustMicrosoftNuGetFeeds setting to false (http://aka.ms/algosettings#trustMicrosoftNuGetFeeds). From what I can tell, it seems like you are able to get all your dependencies from other feeds so your pipeline may not need the Microsoft feeds at all. Does the unblock you? 

Not to say that's the fix of course. Just want to make sure you are not blocked from meeting your deadlines :)

**Comment by nickgoddard777** [comment]
Hi Alex, 

Thanks for your reply, attached is a copy of the successful log. I'll try that workaround now and see if it works, I'll let you know.

[Obfuscated Log Successful.txt](https://github.com/user-attachments/files/31519949/Obfuscated.Log.Successful.txt)

**Comment by nickgoddard777** [comment]
@aholstrup1 thanks, that workaround has worked.

**Comment by dksander** [comment]
1+ for same issue and currently same workaround :-)
Will this be changed to prefer the runtime pack within next version of AL-GO ?

**Comment by ralf-escher** [comment]
1+ for same issue and workaround
